name: Test
on: [ push, pull_request ]
jobs:
  native:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Setup Rust toolchain
      run: rustup show && rustup update
    - name: Build
      run: cargo build  --all-features
    - name: cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-features
